/**
 * Compiled-in fallback for every content key in docs/CONTRACT.md §8.
 *
 * These are the *same* default values the database agent seeds, so a cold,
 * offline first launch still reads correctly. Anything the CMS has edited wins
 * at runtime — see ContentProvider.
 *
 * Keys marked "(extra)" are not in §8: they cover prototype copy that §8 does
 * not enumerate, so that no user-visible string is hardcoded in a screen. They
 * resolve from the CMS too the moment an admin seeds them.
 */
export const defaultContent: Record<string, string> = {
  /* ---------------- common ---------------- */
  'common.app_name': 'Firon Performance',
  'common.app_tagline': 'Train. Track. Transform.',
  'common.logo': '',
  'common.cta_save': 'Save changes',
  'common.cta_close': 'Close',
  'common.toast_saved': 'Details updated ✓',
  'common.empty_generic': 'Nothing here yet',
  /* extra */
  'common.cta_back': 'Back',
  'common.cta_cancel': 'Cancel',
  'common.cta_done': 'Done',
  'common.cta_edit': 'Edit',
  'common.cta_got_it': 'Got it',
  'common.loading': 'Loading…',
  'common.retry': 'Try again',
  'common.error_generic': 'Something went wrong',
  'common.offline_notice': 'Showing saved content — you are offline',
  'common.admin_title': 'Admin account',
  'common.admin_body':
    'Admin accounts are managed from the Firon web CMS. Sign in there to edit content, approve media and review plans.',

  /* ---------------- auth: login ---------------- */
  'auth.login.title': 'Welcome back',
  'auth.login.subtitle': 'Sign in with email or phone',
  'auth.login.identifier_label': 'Email or phone',
  'auth.login.identifier_ph': 'you@email.com',
  'auth.login.password_label': 'Password',
  'auth.login.password_ph': '••••••••',
  'auth.login.remember': 'Remember me',
  'auth.login.forgot': 'Forgot password?',
  'auth.login.submit': 'Sign in',
  'auth.login.new_here': 'New here?',
  'auth.login.create_account': 'Create account',
  'auth.login.hero': '',
  'auth.login.err_identifier': 'Enter a valid email or phone number',
  'auth.login.err_password': 'Password must be at least 6 characters',

  /* ---------------- auth: register ---------------- */
  'auth.register.title': 'Create account',
  'auth.register.subtitle': 'Join Firon Performance in under a minute',
  'auth.register.name_label': 'Full name',
  'auth.register.email_label': 'Email',
  'auth.register.phone_label': 'Phone',
  'auth.register.password_label': 'Password',
  'auth.register.submit': 'Create account & verify',
  'auth.register.otp_hint': "We'll send a one-time code to verify you",
  /* extra */
  'auth.register.name_ph': 'Elie Saide',
  'auth.register.email_ph': 'you@email.com',
  'auth.register.phone_ph': '+961 …',
  'auth.register.password_ph': 'Min. 6 characters',
  'auth.register.err_name': 'Please enter your name',
  'auth.register.err_email': 'Enter a valid email',
  'auth.register.err_phone': 'Enter a valid phone number',
  'auth.register.err_password': 'Password must be at least 6 characters',

  /* ---------------- auth: forgot ---------------- */
  'auth.forgot.title': 'Reset password',
  'auth.forgot.subtitle':
    "Enter your email or phone and we'll send a one-time verification code.",
  'auth.forgot.via_email': 'Send via Email',
  'auth.forgot.via_sms': 'Send via SMS',
  'auth.forgot.submit': 'Send code',
  /* extra */
  'auth.forgot.err_identifier': 'Enter a valid email or phone',
  'auth.forgot.confirm_label': 'Confirm new password',
  'auth.forgot.err_confirm': 'Passwords do not match',
  'auth.forgot.reset_title': 'Choose a new password',
  'auth.forgot.reset_label': 'New password',
  'auth.forgot.reset_submit': 'Save new password',
  'auth.forgot.reset_done': 'Password updated ✓',

  /* ---------------- auth: otp ---------------- */
  'auth.otp.title': 'Verify code',
  'auth.otp.subtitle': 'We sent a 4-digit code to {dest}.',
  'auth.otp.resend_q': "Didn't get it?",
  'auth.otp.resend': 'Resend code',
  'auth.otp.submit': 'Verify',
  'auth.otp.demo_hint': 'Demo code: 1 2 3 4',
  /* extra */
  'auth.otp.err_code': 'Enter the 4-digit code',
  'auth.otp.toast_resent': 'Code resent',
  'auth.otp.toast_verified': 'Account verified ✓',

  /* ---------------- onboarding ---------------- */
  'onboard.title_signup': 'A bit about you',
  'onboard.title_edit': 'My details',
  'onboard.subtitle_signup': 'Coach {coach} uses this to build your training & diet plan',
  'onboard.subtitle_edit': 'Keep these current so coach {coach} can adjust your plans',
  'onboard.gender': 'Gender',
  'onboard.age': 'Age',
  'onboard.height': 'Height (cm)',
  'onboard.weight': 'Weight (kg)',
  'onboard.bodyfat': 'Body fat %',
  'onboard.waist': 'Waist (cm)',
  'onboard.goal': 'Primary goal',
  'onboard.target': 'Target weight (kg)',
  'onboard.sessions': 'Sessions per week',
  'onboard.level': 'Training experience',
  'onboard.cta_signup': 'Finish setup',
  'onboard.cta_edit': 'Save changes',
  'onboard.err_body': 'Enter a realistic height (100–250 cm) and weight (30–300 kg)',
  'onboard.footnote': 'You can change all of this later in your profile',
  /* extra */
  'onboard.optional': '(optional)',
  'onboard.age_ph': 'yrs',
  'onboard.height_ph': '178',
  'onboard.weight_ph': '81.4',
  'onboard.bodyfat_ph': '18.2',
  'onboard.waist_ph': '84',
  'onboard.target_ph': '76',
  'onboard.toast_signup': 'Profile set up — welcome {first} 👋',

  /* ---------------- tabs ---------------- */
  'tabs.client.home': 'Home',
  'tabs.client.train': 'Train',
  'tabs.client.videos': 'Videos',
  'tabs.client.profile': 'Profile',
  'tabs.pt.clients': 'Clients',
  'tabs.pt.plans': 'Plans',
  'tabs.pt.uploads': 'Uploads',
  'tabs.pt.profile': 'Profile',

  /* ---------------- home ---------------- */
  'home.greeting_morning': 'Good morning',
  'home.greeting_afternoon': 'Good afternoon',
  'home.greeting_evening': 'Good evening',
  'home.stat_sessions_label': 'Sessions this wk',
  'home.stat_progress_label': 'Plan progress',
  'home.stat_kcal_label': 'kcal today',
  'home.today_badge': "TODAY'S SESSION",
  'home.today_cta': 'Start workout',
  'home.today_banner': '',
  'home.suggested_title': 'Suggested for you',
  'home.suggested_sub': "Based on your plan & coach {coach}'s library",
  'home.continue_title': 'Continue watching',
  'home.nutrition_title': 'Your nutrition',
  'home.view_all': 'View all',
  'home.promo_video': '',
  /* extra */
  'home.no_session_title': 'No session scheduled today',
  'home.no_session_sub': 'Rest up — coach {coach} has your next session queued.',
  'home.watched_pct': '{pct}% watched',
  'home.nutrition_none': 'No diet plan assigned yet',

  /* ---------------- train ---------------- */
  'train.title': 'Train',
  'train.subtitle': 'Assigned by coach {coach} · updated {when}',
  'train.filter_week': 'This week',
  'train.filter_program': 'Program',
  'train.filter_history': 'History',
  'train.session_progress': 'Session progress',
  'train.cta_check_off': 'Check off session ✓',
  'train.cta_log_exercise': '+ Log an exercise',
  'train.up_next': 'Up next',
  'train.locked_badge': 'Locked',
  'train.complete_title': 'Session complete!',
  'train.demo_cue_default': 'Keep your chest up, brace your core, and control the descent.',
  /* extra */
  'train.empty_title': 'No training plan yet',
  'train.empty_sub': 'Coach {coach} is still building your program.',
  'train.week_title': 'This week',
  'train.days_label': 'days',
  'train.days_done': '{done} of {total} days done · ~{min} min',
  'train.badge_logged': 'Logged',
  'train.badge_today': 'Today',
  'train.badge_completed': 'Completed',
  'train.badge_here': 'You are here',
  'train.badge_upcoming': 'Upcoming',
  'train.day_of': 'Day {n} of {total} · {dur} · with coach {coach}',
  'train.cta_back_today': "Back to today's session",
  'train.cta_repeat': 'Repeat this session',
  'train.cta_locked': 'Preview only · locked',
  'train.toast_already_done': 'Session already completed ✓',
  'train.toast_unlocks': 'Unlocks on {day}',
  'train.demo_title': 'Demo video · coach approved',
  'train.log_title': 'Log an exercise',
  'train.log_sub': 'Something you did outside the plan — coach {coach} will see it in your session.',
  'train.log_name_label': 'Exercise',
  'train.log_name_ph': 'e.g. Lat Pulldown',
  'train.log_err_name': 'Enter an exercise name',
  'train.log_sets_ph': 'Sets',
  'train.log_reps_ph': 'Reps',
  'train.log_weight_ph': 'kg',
  'train.log_notes_label': 'Notes (optional)',
  'train.log_notes_ph': 'How did it feel?',
  'train.log_submit': "Add to today's session",
  'train.log_fallback': 'Logged by you',
  'train.complete_sub': '{title} · {day} checked off',
  'train.complete_minutes': 'minutes',
  'train.complete_exercises': 'exercises',
  'train.complete_week': 'week sessions',
  'train.up_next_sub': 'Day {n} · {when}',
  'train.tomorrow': 'Tomorrow',

  /* ---------------- videos ---------------- */
  'videos.title': 'Videos',
  'videos.empty_category': 'No videos in this category',
  'videos.favorites_chip': '♥ Favorites',
  'videos.sheet_blurb':
    'Coach-approved session from your library. Follow along at your own pace — it counts toward your weekly target.',
  'videos.cta_start': 'Start video',
  'videos.cta_resume': 'Resume video',
  'videos.cta_fav_add': '♡ Save to favorites',
  'videos.cta_fav_remove': '♥ Remove from favorites',
  /* extra */
  'videos.chip_all': 'All',
  'videos.watched_suffix': '{pct}% watched',
  'videos.toast_fav_added': 'Added to favorites',
  'videos.toast_fav_removed': 'Removed from favorites',
  'videos.toast_playing': 'Playing {title}',
  'videos.toast_resuming': 'Resuming {title}',
  'videos.no_source': 'No video file attached yet',

  /* ---------------- search ---------------- */
  'search.title': 'Search',
  'search.subtitle': 'Across videos, plans & content',
  'search.placeholder': "Try 'core', 'yoga', 'plan'…",
  'search.empty': 'Start typing to search your library',
  'search.no_results': 'No results found',
  /* extra */
  'search.group_plans': 'Plans',
  'search.group_videos': 'Videos',

  /* ---------------- nutrition ---------------- */
  'nutrition.title': 'Nutrition',
  'nutrition.subtitle': '{plan} · assigned by coach {coach}',
  'nutrition.protein': 'Protein',
  'nutrition.carbs': 'Carbs',
  'nutrition.fat': 'Fat',
  'nutrition.todays_meals': "Today's meals",
  'nutrition.cta_log_meal': '+ Log a meal',
  /* extra */
  'nutrition.kcal_of': '/ {target} kcal',
  'nutrition.kcal_unit': 'kcal',
  'nutrition.log_title': 'Log a meal',
  'nutrition.log_meal_label': 'Meal',
  'nutrition.log_meal_ph': 'e.g. Post-workout shake',
  'nutrition.log_kcal_label': 'Calories',
  'nutrition.log_kcal_ph': 'kcal',
  'nutrition.log_protein_ph': 'Protein g',
  'nutrition.log_carbs_ph': 'Carbs g',
  'nutrition.log_fat_ph': 'Fat g',
  'nutrition.log_submit': 'Add to today',
  'nutrition.log_err': 'Name the meal and enter its calories',
  'nutrition.toast_logged': 'Meal logged ✓',
  'nutrition.empty': 'No meals planned for today',
  'nutrition.no_plan': 'No diet plan assigned yet',

  /* ---------------- profile (client) ---------------- */
  'profile.title': 'Profile',
  'profile.body_measurements': 'Body measurements',
  'profile.my_goals': 'My goals',
  'profile.cta_edit': 'Edit my details',
  'profile.cta_logout': 'Log out',
  'profile.badge_client': 'Client · Premium plan',
  /* extra */
  'profile.row_gender_age': 'Gender · Age',
  'profile.row_height': 'Height',
  'profile.row_weight': 'Weight',
  'profile.row_bmi': 'BMI',
  'profile.row_bodyfat': 'Body fat',
  'profile.row_waist': 'Waist',
  'profile.row_goal': 'Primary goal',
  'profile.row_target': 'Target weight',
  'profile.row_sessions': 'Weekly sessions',
  'profile.row_level': 'Experience',
  'profile.toast_logout': 'Logged out',

  /* ---------------- pt: roster ---------------- */
  'pt.roster.portal_label': 'Trainer portal',
  'pt.roster.stat_clients': 'Active clients',
  'pt.roster.stat_sessions': 'Sessions this wk',
  'pt.roster.stat_requests': 'New request',
  'pt.roster.roster_title': 'Client roster',
  'pt.roster.badge_new': 'New',
  /* extra */
  'pt.roster.adherence_label': 'adherence',
  'pt.roster.coach_prefix': 'Coach {first}',
  'pt.roster.empty': 'No clients assigned yet',
  'pt.roster.sheet_adherence': 'Adherence',
  'pt.roster.sheet_program': 'Program',
  'pt.roster.sheet_this_week': 'This week',
  'pt.roster.sheet_progress': 'Progress overview',
  'pt.roster.sheet_sessions_done': 'Sessions completed',
  'pt.roster.sheet_weight_change': 'Weight change',
  'pt.roster.sheet_last_active': 'Last active',
  'pt.roster.sheet_diet': 'Diet plan',
  'pt.roster.sheet_plan': 'Plan',
  'pt.roster.sheet_daily_target': 'Daily target',
  'pt.roster.sheet_macros': 'Macros',
  'pt.roster.sheet_meals': 'Meals',
  'pt.roster.sheet_not_assigned': 'Not assigned yet',
  'pt.roster.cta_edit_train': 'Edit training plan',
  'pt.roster.cta_edit_diet': 'Edit diet plan',

  /* ---------------- pt: builder ---------------- */
  'pt.builder.title': 'Plans',
  'pt.builder.subtitle': 'Build a training or diet plan for your client',
  'pt.builder.tab_train': 'Training plan',
  'pt.builder.tab_diet': 'Diet plan',
  'pt.builder.start_from': 'Start from',
  'pt.builder.library_title': 'Exercise library',
  'pt.builder.search_ph': 'Search exercises…',
  'pt.builder.cta_assign_train': 'Assign training plan to {first}',
  'pt.builder.cta_assign_diet': 'Assign diet plan to {first}',
  'pt.builder.daily_targets': 'Daily targets',
  'pt.builder.meals': 'Meals',
  'pt.builder.add_meal': '+ Add meal',
  'pt.builder.no_meals': 'No meals yet — add the first one below',
  /* extra */
  'pt.builder.client_label': 'Client',
  'pt.builder.program_label': 'Program name',
  'pt.builder.program_ph': 'e.g. Fat Loss — Week 5',
  'pt.builder.start_template': 'Template',
  'pt.builder.start_blank': 'Blank',
  'pt.builder.cta_add': '+ Add',
  'pt.builder.cta_added': '✓ Added',
  'pt.builder.plan_label': 'Plan name',
  'pt.builder.plan_ph': 'e.g. Cutting Plan — Week 5',
  'pt.builder.kcal_label': 'Calories (kcal)',
  'pt.builder.protein_label': 'Protein g',
  'pt.builder.carbs_label': 'Carbs g',
  'pt.builder.fat_label': 'Fat g',
  'pt.builder.kcal_badge': '{total} / {target} kcal',
  'pt.builder.meal_add_title': 'Add meal',
  'pt.builder.meal_edit_title': 'Edit meal',
  'pt.builder.meal_slot_label': 'Meal',
  'pt.builder.meal_slot_ph': 'e.g. Breakfast',
  'pt.builder.meal_food_label': 'Food',
  'pt.builder.meal_food_ph': 'e.g. Oats, berries & whey',
  'pt.builder.meal_kcal_label': 'Calories',
  'pt.builder.meal_kcal_ph': 'kcal',
  'pt.builder.meal_err_slot': 'Name the meal',
  'pt.builder.meal_err_food': 'Describe the food',
  'pt.builder.meal_err_kcal': 'Enter the calories',
  'pt.builder.meal_cta_add': 'Add to plan',
  'pt.builder.meal_cta_save': 'Save changes',
  'pt.builder.toast_meal_added': 'Meal added ✓',
  'pt.builder.toast_meal_updated': 'Meal updated ✓',
  'pt.builder.toast_meal_removed': '{slot} removed',
  'pt.builder.toast_train_assigned': 'Training plan assigned to {first} ✓',
  'pt.builder.toast_diet_assigned': 'Diet plan assigned to {first} ✓',
  'pt.builder.err_needs_name': 'Give the plan a name',
  'pt.builder.new_plan': 'new plan',
  'pt.builder.no_clients': 'No clients to build plans for yet',

  /* ---------------- pt: uploads ---------------- */
  'pt.uploads.title': 'Media uploads',
  'pt.uploads.subtitle': 'Exercise demos · reviewed by admin before publishing',
  'pt.uploads.dropzone_title': 'Upload demo video or image',
  'pt.uploads.dropzone_sub': 'MP4 or JPG · routed through admin approval',
  'pt.uploads.mine_title': 'Your uploads',
  'pt.uploads.badge_pending': 'Pending review',
  'pt.uploads.badge_approved': 'Approved',
  'pt.uploads.cta_submit': 'Submit for review',
  /* extra */
  'pt.uploads.sheet_title': 'Upload media',
  'pt.uploads.sheet_sub': 'Will be routed to admin for approval before clients see it.',
  'pt.uploads.title_label': 'Title',
  'pt.uploads.title_ph': 'e.g. Squat depth cue',
  'pt.uploads.category_label': 'Category',
  'pt.uploads.category_ph': 'Strength',
  'pt.uploads.pick_file': 'Tap to choose file',
  'pt.uploads.pick_video': 'Choose video',
  'pt.uploads.pick_image': 'Choose image',
  'pt.uploads.err_title': 'Give the upload a title',
  'pt.uploads.err_file': 'Choose a video or image first',
  'pt.uploads.uploading': 'Uploading… {pct}%',
  'pt.uploads.toast_submitted': 'Submitted for admin approval',
  'pt.uploads.badge_rejected': 'Rejected',
  'pt.uploads.empty': 'Nothing uploaded yet',

  /* ---------------- pt: profile ---------------- */
  'pt.profile.coaching_details': 'Coaching details',
  'pt.profile.certifications': 'Certifications',
  'pt.profile.notifications': 'Notifications',
  'pt.profile.availability': 'Availability',
  'pt.profile.availability_hint': 'Clients can only book sessions inside these hours',
  'pt.profile.cta_copy_weekdays': 'Copy Mon to weekdays',
  'pt.profile.cta_weekend_off': 'Weekend off',
  'pt.profile.cta_save_availability': 'Save availability',
  /* extra */
  'pt.profile.badge_trainer': 'Trainer · Verified',
  'pt.profile.badge_verified': 'Verified',
  'pt.profile.stat_clients': 'Clients',
  'pt.profile.stat_sessions': 'Sessions this wk',
  'pt.profile.stat_adherence': 'Avg adherence',
  'pt.profile.row_studio': 'Studio',
  'pt.profile.row_rate': 'Session rate',
  'pt.profile.row_since': 'Coaching since',
  'pt.profile.edit_title': 'Edit profile',
  'pt.profile.edit_sub': 'Shown to your clients and on your plans',
  'pt.profile.name_label': 'Full name',
  'pt.profile.title_label': 'Title',
  'pt.profile.email_label': 'Email',
  'pt.profile.phone_label': 'Phone',
  'pt.profile.studio_ph': 'Studio',
  'pt.profile.rate_ph': 'Rate',
  'pt.profile.err_name': 'Please enter your name',
  'pt.profile.err_email': 'Enter a valid email',
  'pt.profile.toast_saved': 'Profile updated ✓',
  'pt.profile.pref_new_clients': 'New client requests',
  'pt.profile.pref_reminders': 'Session reminders',
  'pt.profile.pref_adherence': 'Weekly adherence report',
  'pt.profile.on': 'On',
  'pt.profile.off': 'Off',
  'pt.profile.availability_edit_title': 'Edit availability',
  'pt.profile.availability_edit_sub': 'Set the hours you take bookings each day',
  'pt.profile.availability_tap': 'Tap to edit your hours',
  'pt.profile.availability_err': 'Each open day needs a start time earlier than its end time',
  'pt.profile.cta_edit_hours': 'Edit hours',
  'pt.profile.toast_copied': 'Mon hours copied to Tue–Fri',
  'pt.profile.toast_weekend_off': 'Weekend set to off',
  'pt.profile.toast_availability': 'Availability saved · {open} open ✓',
  'pt.profile.day_off': 'Off',

  /* ---------------- guest preview (CONTRACT §13.4) ---------------- */
  'guest.banner_title': 'Preview mode',
  'guest.banner_body': 'Sign in to start training with your coach',
  'guest.banner_cta': 'Sign in',
  'guest.gate_title': 'Sign in to continue',
  'guest.gate_body': 'Create an account or sign in to use this.',
  /** replaces the time-of-day greeting while previewing */
  'guest.greeting': 'Welcome',
  /** stand-in for the signed-in client's name */
  'guest.display_name': 'Athlete',
  /** fills the {coach} interpolations while previewing */
  'guest.coach_name': 'Sara',
  'guest.profile_badge': 'Preview · Not signed in',
  'guest.profile_cta': 'Sign in to see your real plan',

  /* ---------------- notifications ---------------- */
  'notifications.title': 'Notifications',
  'notifications.empty': "You're all caught up",
  /* extra */
  'notifications.mark_all': 'Mark all read',
  'notifications.unread_one': '1 unread',
  'notifications.unread_many': '{n} unread',
  'notifications.all_read': 'All caught up',
};

/** Keys that hold media (image/video) rather than copy. */
export const mediaKeys: readonly string[] = [
  'common.logo',
  'auth.login.hero',
  'home.today_banner',
  'home.promo_video',
];

export default defaultContent;
